version: '3.8'

services:
  thakali-site:
    image: thakali-site:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thakali-container
    ports:
      - "3000:80"
    restart: always
